import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

/**
 * A simple GUI calculator program in Java using Swing.
 * This program provides a window with buttons for numbers and basic arithmetic operations.
 */
public class javaproject implements ActionListener {

    // Swing components for the calculator UI
    JFrame frame;
    JTextField textfield;
    JButton[] numberButtons = new JButton[10];
    JButton[] functionButtons = new JButton[9];
    JButton addButton, subButton, mulButton, divButton;
    JButton decButton, equButton, delButton, clrButton, negButton;
    JPanel panel;

    // Fonts for styling
    Font myFont = new Font("Inter", Font.BOLD, 30);

    // Variables to hold the numbers and the result of the calculation
    double num1 = 0, num2 = 0, result = 0;
    char operator;

    /**
     * Constructor to set up the calculator's GUI.
     */
    public javaproject() {

        // --- Frame Setup ---
        frame = new JFrame("Calculator");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(420, 550);
        frame.setLayout(null);
        frame.setResizable(false); // User cannot resize the window

        // --- Textfield (Display) Setup ---
        textfield = new JTextField();
        textfield.setBounds(50, 25, 300, 50);
        textfield.setFont(myFont);
        textfield.setEditable(false); // User cannot type directly into the display
        textfield.setHorizontalAlignment(JTextField.RIGHT);

        // --- Button Setup ---
        addButton = new JButton("+");
        subButton = new JButton("-");
        mulButton = new JButton("*");
        divButton = new JButton("/");
        decButton = new JButton(".");
        equButton = new JButton("=");
        delButton = new JButton("Del");
        clrButton = new JButton("C");
        negButton = new JButton("(-)");

        // Add function buttons to an array for easier handling
        functionButtons[0] = addButton;
        functionButtons[1] = subButton;
        functionButtons[2] = mulButton;
        functionButtons[3] = divButton;
        functionButtons[4] = decButton;
        functionButtons[5] = equButton;
        functionButtons[6] = delButton;
        functionButtons[7] = clrButton;
        functionButtons[8] = negButton;

        // Set properties and add ActionListener for each function button
        for (int i = 0; i < 9; i++) {
            functionButtons[i].addActionListener(this);
            functionButtons[i].setFont(myFont);
            functionButtons[i].setFocusable(false); // Removes the focus border
        }

        // Create and set properties for number buttons (0-9)
        for (int i = 0; i < 10; i++) {
            numberButtons[i] = new JButton(String.valueOf(i));
            numberButtons[i].addActionListener(this);
            numberButtons[i].setFont(myFont);
            numberButtons[i].setFocusable(false);
        }

        // Set bounds for the clear, delete, and negate buttons
        negButton.setBounds(50, 430, 100, 50);
        delButton.setBounds(150, 430, 100, 50);
        clrButton.setBounds(250, 430, 100, 50);

        // --- Panel Setup (for number and operator buttons) ---
        panel = new JPanel();
        panel.setBounds(50, 100, 300, 300);
        panel.setLayout(new GridLayout(4, 4, 10, 10));
        panel.setBackground(new color ( ))// 4x4 grid with 10px spacing

        // Add buttons to the panel in a standard calculator layout
        panel.add(numberButtons[1]);
        panel.add(numberButtons[2]);
        panel.add(numberButtons[3]);
        panel.add(addButton);
        panel.add(numberButtons[4]);
        panel.add(numberButtons[5]);
        panel.add(numberButtons[6]);
        panel.add(subButton);
        panel.add(numberButtons[7]);
        panel.add(numberButtons[8]);
        panel.add(numberButtons[9]);
        panel.add(mulButton);
        panel.add(decButton);
        panel.add(numberButtons[0]);
        panel.add(equButton);
        panel.add(divButton);

        // --- Add all components to the frame ---
        frame.add(panel);
        frame.add(negButton);
        frame.add(delButton);
        frame.add(clrButton);
        frame.add(textfield);
        frame.setVisible(true); // Make the frame visible
    }

    /**
     * Main method to create an instance of the calculator.
     */
    public static void main(String[] args) {
        javaproject calc = new javaproject();
    }

    /**
     * Handles all button click events.
     * @param e The ActionEvent object generated by the button click.
     */
    @Override
    public void actionPerformed(ActionEvent e) {

        // Check if the source of the event was a number button
        for (int i = 0; i < 10; i++) {
            if (e.getSource() == numberButtons[i]) {
                textfield.setText(textfield.getText().concat(String.valueOf(i)));
            }
        }

        // Check for decimal button
        if (e.getSource() == decButton) {
            if (!textfield.getText().contains(".")) {
                 textfield.setText(textfield.getText().concat("."));
            }
        }

        // Check for add button
        if (e.getSource() == addButton) {
            num1 = Double.parseDouble(textfield.getText());
            operator = '+';
            textfield.setText("");
        }

        // Check for subtract button
        if (e.getSource() == subButton) {
            num1 = Double.parseDouble(textfield.getText());
            operator = '-';
            textfield.setText("");
        }

        // Check for multiply button
        if (e.getSource() == mulButton) {
            num1 = Double.parseDouble(textfield.getText());
            operator = '*';
            textfield.setText("");
        }

        // Check for divide button
        if (e.getSource() == divButton) {
            num1 = Double.parseDouble(textfield.getText());
            operator = '/';
            textfield.setText("");
        }

        // Check for equals button
        if (e.getSource() == equButton) {
            num2 = Double.parseDouble(textfield.getText());

            switch (operator) {
                case '+':
                    result = num1 + num2;
                    break;
                case '-':
                    result = num1 - num2;
                    break;
                case '*':
                    result = num1 * num2;
                    break;
                case '/':
                    if (num2 != 0) {
                        result = num1 / num2;
                    } else {
                        textfield.setText("Error: Div by 0");
                        return;
                    }
                    break;
            }
            textfield.setText(String.valueOf(result));
            num1 = result; // Use the result for the next calculation
        }

        // Check for clear button
        if (e.getSource() == clrButton) {
            textfield.setText("");
            num1 = 0;
            num2 = 0;
            result = 0;
        }

        // Check for delete button
        if (e.getSource() == delButton) {
            String string = textfield.getText();
            textfield.setText("");
            for (int i = 0; i < string.length() - 1; i++) {
                textfield.setText(textfield.getText() + string.charAt(i));
            }
        }
        
        // Check for negate button
        if(e.getSource() == negButton) {
            if (!textfield.getText().isEmpty()) {
                double temp = Double.parseDouble(textfield.getText());
                temp *= -1;
                textfield.setText(String.valueOf(temp));
            }
        }
    }
}
